# SQL aula 25 - TIPOS DE DADOS

/*
-- DESCRIÇÃO
    > BOLEANOS 
        ## POR PADRÃO ELE É INICIALIZADO COMO NULO, E PODE RECEBER TANTO 1 OU 0
        TIPO = BIT

    > CARACTERES
        ## TAMANHO FIXO - TIPO = CHAR > PERMIRTE INSERIR ATÉ UMA QUANTIDADE DE CARACTERS E SEMPRE OCUPA TODO ESPAÇO DA MEMÓRIA RESERVADO. EXEMPLO = 10/50.
        ## TAMANHO VARIÁVEIS - TIPO = VACHAR OU NVARCHAR > PERMIRTE INSERIR ATÉ UMA QUANTIDE QUE FOR DEFINIDA, PORÉM SÓ USA O ESPAÇO QUE FOR PREECHIDO 10/50.

    > NÚMEROS
        ## TIPO TINYINT = NÃO TEM PARTE VALOR FRACIONADO (EX: 1.43, 24.23) SOMENTE 1,123123,324324,313123 ETC...
        ## TIPO SMALLINT =
        ## TIPO INT =
        ## TIPO BIGINT =
        ## TIPO NUMERIC E DECIMAL =



    > TEMPORAIS

- OBS.
*/

-- SINTASE 

SELECT nome_coluna
FROM tabela a, tabela b
WHERE condicao

-- EXEMPLO 
