-- # SQL aula 27 - CREATE TABLE


CREATE TABLE Canal (
CanalId int Primary Key,
Nome varchar(150) NOT NULL,
ContagemInscritos INT DEFAULT 0,
DataCriacao DATETIME NOT NULL
);

SELECT *
FROM Canal

-- # CRIANDO A TABELA COM FOREIGN KEY

CREATE TABLE Video (
VideoId INT PRIMARY KEY,
Nome VARCHAR(150) NOT NULL,
Visualizacoes INT DEFAULT 0,
Deslikes INT DEFAULT 0,
Duracao INT NOT NULL,
CanalID INT FOREIGN KEY REFERENCES Canal(CanalID)
);

SELECT * 
FROM Video

-- DESAFIOS
-- ## ENCONTRE DUAS COISAS NA SUA CASA QUE PODEM TORNAR TABELAS E CRIE 2 TABELAS QUE TEM NO MINIMO 1 RELACIONAMENTO COM A OUTRA!