# SQL aula 19 - SELF JOIN

/*
-- DESCRIÇÃO
    > O OPERADOR UNION COMBINA DOIS OU MAIS RESULTADOS DE UM SELECT EM UM RESULTADO APENAS.

- OBS. ELE REMOVE OS DADOS DUPLICADOS
*/

-- SINTASE 

SELECT nome_coluna
FROM tabela a, tabela b
WHERE condicao

-- EXEMPLO 
