-- LEFT OUTER JOIN
-- LEFT JOIN

-- QUERO DESCOBRIR QUAIS PESSOAS TEM UM CARTÃO DE CREDITO REGISTRADO

SELECT *
FROM Person.Person PP
INNER JOIN Sales.PersonCreditCard PC
ON PP.BusinessEntityID = PC.BusinessEntityID
-- INNER JOIN: 19118

SELECT *
FROM Person.Person PP
LEFT JOIN Sales.PersonCreditCard PC
ON PP.BusinessEntityID = PC.BusinessEntityID
WHERE PC.BusinessEntityID IS NULL --PARA DESCOBRIR A DIFERENÇA DE QUEM NÃO TEM CARTÕES CADASTRADOS
-- LEFT JOIN: 19972
