SELECT 
--SQL Server, Postgres, Oracle, mySql

SELECT coluna1,coluna2,
FROM tabela1

SELECT *
FROM tabela

A EQUIPE DE MARKETING PRECISA DE FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES 
E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.

first name, last name

