SELECT FirstName, COUNT (FirstName) AS "QUANTIDADE"
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 10
ORDER BY FirstName ASC

-- SABER QUAIS PRODUTOS QUE NO TOTAL DE VENDAS ESTÃO ENTRE 162K A 500K

SELECT ProductID, SUM(LineTotal) AS "TOTAL"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000

-- SABER QUAIS NOMES NO SISTEMA TEM UMA OCORRÊNCIA MAIOR QUE 10X, PORÉM SOMENTE ONDE O
-- TITULO É MRS. (APLICAÇÃO DO WHERE E HAVING NA MESMA QUERY!!!)

SELECT FirstName, COUNT (FirstName) AS "QUANTIDADE"
FROM Person.Person
WHERE Title = 'MR.'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10
ORDER BY FirstName ASC

-- EXERCICIOS 01

SELECT StateProvinceID, COUNT (StateProvinceID) AS "QUANTIDADE"
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000
ORDER BY StateProvinceID ASC

-- EXERCICIOS 02

SELECT ProductID, AVG(LineTotal) AS "MEDIA"
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000000
ORDER BY MEDIA DESC -- DEPOIS DE RENOMEAR UMA COLUNA, EU POSSO USAR ELA PARA ORDENA-LA
